name: Workflow Test
on: push

jobs:
  docker:
    runs-on: [self-hosted, ARM64]
    steps:
      - run: pwd
      - run: docker run --entrypoint "validate" --name "github-runner" -t rv32sim-container:latest 
        continue-on-error: True
      - run: docker cp github-runner:/home/riscofuser/rv32sim_validation/riscof_work/report.html .
      - run: docker rm github-runner
      - uses: actions/upload-artifact@v4
        with:
          name: test_results
          path: /Users/sheasewall/Files/Code/riscv/rv32sim/actions-runner/_work/CPUSim/CPUSim/report.html
