name: Workflow Test
on: push
env:
  RELEASE_NAME: ghrlatest
  
jobs:
  docker:
    runs-on: [self-hosted, ARM64]
    steps:
      - run: pwd
      - run: /Users/sheasewall/Files/Code/riscv/rv32sim-container/build_image.sh base "$GITHUB_REF_NAME"-"$RELEASE_NAME"
      - run: docker run --entrypoint "validate" --name "github-runner" -t rv32sim-container:base-"$GITHUB_REF_NAME"-"$RELEASE_NAME"
        continue-on-error: True
      - run: docker cp github-runner:/home/riscofuser/rv32sim_validation/riscof_work/report.html .
      - run: docker rm github-runner
      - uses: actions/upload-artifact@v4
        with:
          name: test_results
          path: /Users/sheasewall/Files/Code/riscv/rv32sim/actions-runner/_work/CPUSim/CPUSim/report.html

  display:
    needs: docker
    runs-on: [self-hosted, ARM64]
    steps:
      - run: echo "$(grep -Eo '[0-9]+Passed' report.html | grep -Eo '[0-9]+') Passed" >> "$GITHUB_STEP_SUMMARY"
      - run: echo "$(grep -Eo '[0-9]+Failed' report.html | grep -Eo '[0-9]+') Failed" >> "$GITHUB_STEP_SUMMARY"
