name: Workflow Test
on: push

jobs:
  docker:
    runs-on: [self-hosted, ARM64]
    steps:
      - run: pwd
      - run: cp /Users/sheasewall/Files/Code/riscv/riscof-container/riscof.tar.gz .
      - run: ls
